"""add_gitlab_support_and_update_user_model

Revision ID: 4f114b7a9644
Revises: 7f80b3d784ed
Create Date: 2025-10-12 01:03:13.273071

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f114b7a9644'
down_revision: Union[str, None] = '7f80b3d784ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gitlab_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gitlab_access_token', sa.String(), nullable=True))
    op.alter_column('users', 'github_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_gitlab_id'), 'users', ['gitlab_id'], unique=True)
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_gitlab_id'), table_name='users')
    op.alter_column('users', 'github_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'gitlab_access_token')
    op.drop_column('users', 'github_access_token')
    op.drop_column('users', 'gitlab_id')
    # ### end Alembic commands ###
