"""add_branch_to_deployments

Revision ID: 7f80b3d784ed
Revises: 21655a64fa98
Create Date: 2025-10-11 14:46:06.194020

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f80b3d784ed'
down_revision: Union[str, None] = '21655a64fa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('deployments', sa.Column('branch', sa.String(), nullable=True))
    
    # Update existing records to have a default branch
    op.execute("UPDATE deployments SET branch = 'main' WHERE branch IS NULL")
    
    # Now make the column not nullable
    op.alter_column('deployments', 'branch', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'branch')
    # ### end Alembic commands ###
