---
- name: Configure deployment instance
  hosts: web
  become: yes
  vars:
    app_dir: /home/ubuntu/app
    
  tasks:
    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 300
        delay: 5
        
    - name: Ensure system is fully booted
      command: systemctl is-system-running
      register: system_status
      until: system_status.stdout.find("running") != -1 or system_status.stdout.find("degraded") != -1
      retries: 30
      delay: 10
      ignore_errors: yes
      
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      register: user_group_result
      
    - name: Show user group update result
      debug:
        msg: "User group updated: {{ user_group_result.changed }}"
      
    # Note: We don't force reset SSH connection because it causes issues
    # Instead, we'll use 'sg docker' command in subsequent playbooks
    # This allows docker commands to run with the docker group even though
    # the SSH session hasn't picked up the new group membership yet
    
    - name: Install Git
      apt:
        name: git
        state: present
        
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu
        
    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes
      become_user: ubuntu
      register: git_result
      retries: 3
      delay: 5
      
    - name: Show git clone result
      debug:
        msg: "Git clone result: {{ git_result }}"
        
    - name: Create .env file
      copy:
        content: |
          {% for key, value in env_vars.items() %}
          {{ key }}={{ value }}
          {% endfor %}
        dest: "{{ app_dir }}/.env"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      when: env_vars is defined and env_vars | length > 0
      
    - name: Verify Docker service is running
      shell: |
        # Use sg docker to ensure group permissions work even on first run
        sg docker -c "docker info" > /dev/null 2>&1 && echo "Docker OK" || echo "Docker check failed"
      become_user: ubuntu
      register: docker_test
      retries: 5
      delay: 3
      until: docker_test.stdout.find("Docker OK") != -1
      
    - name: Show Docker test result
      debug:
        msg: "Docker test result: {{ docker_test.stdout }}"