---
- name: Deploy application
  hosts: all
  become: yes
  vars:
    app_dir: /home/ubuntu/app
  tasks:
    # Stop existing containers
    - name: Stop existing containers
      shell: |
        cd {{ app_dir }}
        docker-compose down || true
      become_user: ubuntu
      ignore_errors: yes
      
    # Start application with docker-compose
    - name: Start application with docker-compose
      shell: |
        cd {{ app_dir }}
        docker-compose up -d
      become_user: ubuntu
        
    # Wait a moment for containers to start
    - name: Wait for containers to start
      pause:
        seconds: 10
      
    # Verify deployment (basic check that containers are running)
    - name: Verify containers are running
      shell: |
        cd {{ app_dir }}
        docker-compose ps
      become_user: ubuntu
      register: compose_status
      
    - name: Display container status
      debug:
        msg: "Container status: {{ compose_status.stdout }}"